from zoneinfo import ZoneInfo


AELF_API_BASE = "https://api.aelf.org/v1"
APP_TIMEZONE = ZoneInfo("Africa/Ouagadougou")

AELF_ZONES = {
    "Calendrier romain": "romain",
    "Afrique du Nord": "afrique",
    "Belgique": "belgique",
    "Canada": "canada",
    "France": "france",
    "Luxembourg": "luxembourg",
    "Monaco": "monaco",
    "Suisse": "suisse",
}

THEME_RULES = {
    "espérance": {
        "keywords": ["esperance", "espere", "confiance", "attendre", "promesse", "avenir", "console", "relever"],
        "focus": "une espérance qui nous relève et nous fait avancer avec confiance",
        "church": "qu'elle demeure un signe d'espérance et de consolation pour tous",
        "world": "que l'espérance l'emporte sur le découragement, la peur et les divisions",
        "suffering": "qu'ils trouvent des personnes capables de les soutenir et de raviver leur espérance",
        "community": "qu'elle sache encourager ceux qui traversent l'épreuve et porter les plus fragiles",
    },
    "conversion": {
        "keywords": ["conversion", "convert", "repent", "changer", "retour", "coeur nouveau", "chemin", "revenir"],
        "focus": "un appel à la conversion du cœur et à un choix renouvelé pour Dieu",
        "church": "qu'elle annonce avec vérité et miséricorde l'appel du Christ à la conversion",
        "world": "que les responsables sachent renoncer à ce qui nourrit l'injustice et choisir le bien commun",
        "suffering": "qu'ils rencontrent des chemins de relèvement, de pardon et de recommencement",
        "community": "qu'elle accepte de se laisser transformer par la Parole et de vivre une foi plus cohérente",
    },
    "miséricorde": {
        "keywords": ["misericorde", "pitie", "compassion", "pardonne", "pardon", "peche", "reconcil", "tendresse"],
        "focus": "la miséricorde de Dieu qui pardonne, relève et ouvre un avenir",
        "church": "qu'elle soit une maison de miséricorde, de pardon et de réconciliation",
        "world": "que la justice s'exerce sans haine et que les peuples apprennent les chemins du pardon",
        "suffering": "qu'ils expérimentent la compassion de Dieu à travers une présence fraternelle",
        "community": "qu'elle sache demander pardon, pardonner et reconstruire les relations blessées",
    },
    "foi": {
        "keywords": ["foi", "croire", "cru", "croyant", "confiance", "seigneur", "parole", "ecouter"],
        "focus": "une foi vivante, nourrie par l'écoute de la Parole et la confiance en Dieu",
        "church": "que sa foi demeure ferme et qu'elle aide chacun à rencontrer le Christ vivant",
        "world": "que les hommes et les femmes de bonne volonté gardent confiance dans la force du bien",
        "suffering": "que leur foi et celle de leurs proches soient soutenues dans les moments d'épreuve",
        "community": "qu'elle grandisse dans l'écoute de la Parole, la prière et le témoignage quotidien",
    },
    "justice": {
        "keywords": ["justice", "juste", "droit", "pauvre", "opprime", "injustice", "juge", "equite"],
        "focus": "la justice de Dieu qui nous rend attentifs aux pauvres, aux petits et au bien de tous",
        "church": "qu'elle défende la dignité de toute personne et fasse entendre la voix des plus faibles",
        "world": "que les gouvernants recherchent la justice, la vérité et le bien commun plutôt que les intérêts particuliers",
        "suffering": "que les victimes d'injustice trouvent soutien, protection et réparation",
        "community": "qu'elle refuse l'indifférence et pose des gestes concrets de solidarité et de justice",
    },
    "paix": {
        "keywords": ["paix", "reconcili", "ennemi", "guerre", "division", "unite", "frere", "fraternite"],
        "focus": "la paix reçue de Dieu et construite dans la vérité, la justice et la fraternité",
        "church": "qu'elle travaille sans relâche à l'unité, au dialogue et à la réconciliation",
        "world": "que cessent les violences et que les responsables des nations cherchent des chemins durables de paix",
        "suffering": "que les victimes de guerre, de violence ou de déplacement trouvent sécurité et secours",
        "community": "qu'elle devienne un lieu de réconciliation, d'écoute et de fraternité véritable",
    },
    "service": {
        "keywords": ["servir", "service", "serviteur", "donner", "laver", "petit", "humble", "ministre"],
        "focus": "le chemin du service humble, à l'exemple du Christ qui se donne pour les autres",
        "church": "que ses pasteurs et tous les baptisés servent avec humilité, disponibilité et charité",
        "world": "que l'autorité soit vécue comme un service du bien commun et des plus vulnérables",
        "suffering": "qu'ils rencontrent des personnes disponibles pour les accompagner avec respect et délicatesse",
        "community": "qu'elle découvre la joie de servir et de prendre soin les uns des autres",
    },
    "charité": {
        "keywords": ["aime", "amour", "charite", "prochain", "frere", "don", "coeur", "aimer"],
        "focus": "l'amour de Dieu qui nous apprend à aimer concrètement nos frères et sœurs",
        "church": "que toute son action soit enracinée dans la charité du Christ",
        "world": "que la solidarité et le respect de la dignité humaine inspirent les choix collectifs",
        "suffering": "qu'ils soient entourés d'une charité concrète, fidèle et respectueuse",
        "community": "qu'elle grandisse dans l'attention fraternelle, le partage et la charité vécue",
    },
    "Esprit Saint": {
        "keywords": ["esprit saint", "esprit", "souffle", "don de l'esprit", "pentecote", "consolateur"],
        "focus": "l'action de l'Esprit Saint qui éclaire, fortifie et envoie les disciples",
        "church": "qu'elle se laisse conduire par l'Esprit Saint dans sa mission et son discernement",
        "world": "que l'Esprit de sagesse inspire les artisans de paix, de justice et de fraternité",
        "suffering": "qu'ils reçoivent force, consolation et paix dans l'épreuve",
        "community": "qu'elle accueille les dons de l'Esprit et les mette au service de tous",
    },
    "résurrection": {
        "keywords": ["resurrection", "ressuscite", "vie eternelle", "tombeau", "vivant", "mort", "relever", "paques"],
        "focus": "la victoire du Christ sur la mort et l'espérance de la vie nouvelle",
        "church": "qu'elle annonce avec joie le Christ ressuscité et témoigne de la vie plus forte que la mort",
        "world": "que les peuples marqués par la violence et la mort découvrent des chemins de vie et de paix",
        "suffering": "qu'ils soient soutenus par l'espérance pascale et la proximité fraternelle",
        "community": "qu'elle vive comme un peuple de ressuscités, capable de recommencer et de transmettre la joie de l'Évangile",
    },
    "mission": {
        "keywords": ["envoye", "mission", "temoin", "annoncer", "evangile", "nations", "disciples", "allez"],
        "focus": "l'appel à devenir disciples missionnaires et témoins de l'Évangile",
        "church": "qu'elle annonce l'Évangile avec courage, simplicité et respect de chaque personne",
        "world": "que le témoignage des chrétiens contribue au dialogue, à la paix et au service de tous",
        "suffering": "que personne ne soit oublié dans l'annonce et la proximité fraternelle de l'Église",
        "community": "qu'elle ose témoigner de sa foi par ses paroles, ses choix et son service",
    },
    "alliance": {
        "keywords": ["alliance", "fidelite", "promesse", "peuple", "commandement", "loi", "heritage"],
        "focus": "la fidélité de Dieu à son alliance et notre réponse confiante à son appel",
        "church": "qu'elle demeure fidèle à l'Évangile et garde vivante la mémoire des merveilles de Dieu",
        "world": "que les engagements pris au service de la paix, de la justice et de la dignité humaine soient respectés",
        "suffering": "qu'ils fassent l'expérience d'une présence fidèle qui ne les abandonne pas",
        "community": "qu'elle apprenne la fidélité dans la prière, les engagements et les relations fraternelles",
    },
    "prière": {
        "keywords": ["priere", "prier", "demandez", "veillez", "supplier", "louer", "rendre grace", "pere"],
        "focus": "une prière confiante qui ouvre le cœur à Dieu et transforme notre manière de vivre",
        "church": "qu'elle soit une communauté de prière, d'écoute et d'intercession pour le monde",
        "world": "que les décisions importantes soient éclairées par la recherche sincère du bien et de la vérité",
        "suffering": "qu'ils trouvent dans la prière et la présence fraternelle force et consolation",
        "community": "qu'elle redécouvre la prière personnelle, familiale et communautaire comme source de fidélité",
    },
    "humilité": {
        "keywords": ["humble", "humilite", "petit", "dernier", "serviteur", "abaisse", "pauvre de coeur"],
        "focus": "l'humilité qui nous rend disponibles à Dieu et attentifs aux autres",
        "church": "qu'elle serve sans recherche de prestige et demeure proche des petits et des pauvres",
        "world": "que ceux qui exercent des responsabilités sachent écouter, reconnaître leurs limites et servir",
        "suffering": "qu'ils soient accueillis avec respect, sans jugement ni condescendance",
        "community": "qu'elle apprenne à écouter, à servir et à donner une place à chacun",
    },
    "eucharistie": {
        "keywords": ["pain", "coupe", "manger", "boire", "corps", "sang", "eucharistie", "fraction"],
        "focus": "le don du Christ qui nourrit son peuple et nous rassemble dans l'unité",
        "church": "qu'elle célèbre l'Eucharistie avec foi et en traduise les fruits dans la charité",
        "world": "que le partage et la solidarité l'emportent sur l'accaparement et l'exclusion",
        "suffering": "qu'ils reçoivent le soutien de la communauté et la consolation du Christ",
        "community": "que la communion eucharistique fasse grandir entre nous le partage, le pardon et l'unité",
    },
    "Royaume": {
        "keywords": ["royaume", "regne", "roi", "semence", "vigne", "moisson", "tresor", "parabole"],
        "focus": "le Royaume de Dieu qui grandit au milieu de nous et appelle notre réponse",
        "church": "qu'elle serve humblement la croissance du Royaume par l'annonce, la justice et la charité",
        "world": "que les choix humains favorisent ce qui fait grandir la paix, la dignité et la fraternité",
        "suffering": "qu'ils trouvent dans la communauté des signes concrets du Royaume qui relève et console",
        "community": "qu'elle sache reconnaître et faire grandir les semences du Royaume dans la vie quotidienne",
    },
}
